version: '3.9'
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache:latest
    command: --database.dbPath=/data
    ports:
      - 8545:8545
    restart: always
    volumes:
      - ganache-data:/data

  main-server:
    container_name: main-server
    build: 
      context: ./main-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - postgres
    configs:
      - source: main-server-config
        target: /app/config/config.json

  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plohub
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./main-server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mysql:
    container_name: mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=plohub
    ports:
      - 3307:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  ganache-data:
    driver: local
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  
configs:
  main-server-config:
    file: ./main-server/config/config.docker.json