version: '3.9'
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache:latest
    command: --database.dbPath=/data --wallet.accounts 0xf3aff74e76ab06ba866303284853ab6eef61028409b85d918dbd65ddbb6cf879,10000000000000000000000 --wallet.accounts 0x81adba35ea1df077bcd938abc83ee1fa3635da98f9c075892f16a458c071fbd3,10000000000000000000000
    ports:
      - 8545:8545
    restart: always
    volumes:
      - ganache-data:/data
    networks:
      - blockchain-tier

  main-server:
    container_name: main-server
    build: 
      context: ./main-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    configs:
      - source: main-server-config
        target: /app/config/config.json
    networks:
      - back-tier
    depends_on:
      - postgres

  contract-server:
    container_name: contract-server
    build:
      context: ./contract-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /tmp/contract-server/npm_cache:/root/.npm:z
      - ./contract-server/abi:/usr/src/app/abi:z
      - ./contract-server/config:/usr/src/app/config:z
      - ./contract-server/controllers:/usr/src/app/controllers:z
      - ./contract-server/loaders:/usr/src/app/loaders:z
      - ./contract-server/models:/usr/src/app/models:z
      - ./contract-server/routes:/usr/src/app/routes:z
      - ./contract-server/.env:/usr/src/app/.env:z
      - ./contract-server/index.js:/usr/src/app/index.js:z
    networks:
      - back-tier
      - blockchain-tier
    depends_on:
      - mysql
      - ganache

  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plohub
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier

  mysql:
    container_name: mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=plohub
    ports:
      - 5000:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blockchain-tier

  caddy:
    container_name: caddy
    image: caddy:2.6.4-alpine
    command: caddy reverse-proxy --from localhost --to main-server:4000
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - caddy-data:/data
    networks:
      - back-tier
    depends_on:
      - main-server

volumes:
  ganache-data:
    driver: local
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  caddy-data:
    driver: local

networks:
  back-tier:
    name: back-tier
    driver: bridge
  blockchain-tier:
    name: blockchain-tier
    driver: bridge
  
configs:
  main-server-config:
    file: ./main-server/config/config.docker.json