version: '3.9'
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    restart: always

  main-server:
    container_name: main-server
    build: 
      context: ./main-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plohub
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./main-server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres-data:
    driver: local
  