export const SET_EMAIL = "SET_EMAIL";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_NICKNAME = "SET_NICKNAME";
export const SET_LEVEL = "SET_LEVEL";
export const SET_TOKEN_BALANCE = "SET_TOKEN_BALANCE";
export const SET_DAILY_TOKEN_BALANCE = "SET_DAILY_TOKEN_BALANCE";
export const SET_ETH_BALANCE = "SET_ETH_BALANCE";
