CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "hashed_password" varchar NOT NULL,
  "nickname" varchar NOT NULL DEFAULT 'unnamed',
  "level" smallint NOT NULL DEFAULT 1,
  "address" varchar NOT NULL,
  "eth_amount" bigint DEFAULT 0 NOT NULL,
  "token_amount" bigint DEFAULT 0 NOT NULL,
  "latest_login_date" date,
  "daily_token" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "posts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "is_admin" boolean DEFAULT false NOT NULL,
  "title" varchar NOT NULL,
  "content" text NOT NULL,
  "category" smallint NOT NULL,
  "reward_token" integer DEFAULT 0 NOT NULL,
  "nftnized" boolean DEFAULT false NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "type" smallint NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "reward_token" int DEFAULT 0 NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "media" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
